# Generated by Django 4.1.3 on 2022-12-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(default=2, max_length=25, verbose_name='image'),
            preserve_default=False,
        ),
    ]
