# Generated by Django 4.1.3 on 2023-01-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_en',
            field=models.CharField(max_length=50),
        ),
    ]
