# Generated by Django 4.1.3 on 2023-01-18 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_alter_word_word_alter_word_word_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='BackGroundWord',
        ),
        migrations.CreateModel(
            name='GirlWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('word_en', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generate.type')),
            ],
        ),
    ]
